### ISSUE TITLE
ipython crashes when launced from dir simlammps

### ISSUE THREAD

**Issue by jeremy-rutman** [simphony/simphony-lammps#113] opened 2016-01-20 10:13 UTC
problem exactly as here:
https://github.com/ipython/ipython/issues/6486

naming a directory io apparently will cause trouble

**Comment by mehdisadeghi** [comment] 2016-09-08 18:29
It works for me. However I can not import `simlammps` package inside ipython. Do you still encounter this problem? What is your '$PYTHONPATH' BTW?

**Comment by mehdisadeghi** [comment] 2017-09-28 13:19
@jeremy-rutman I can't reproduce this issue (probably it is fixed by latest updates to ipython). Closing. Feel free to reopen if you experience any problems.

**Closed by mehdisadeghi** 2017-09-28 13:19 UTC
